# Generated by Django 5.1.2 on 2024-11-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
